version : "3.5"
volumes : 
  wordpress: 

services :
  wordpress:
    image: wordpress:42
    container_name: wordpress
    build: ./requirements/wordpress/.
    ports:
      - 9000
    volumes:
      - wordpress:/var/www/html
    restart: always
  nginx:
    image: nginx:42
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress